baseURL: 'https://fhrzn.github.io'
languageCode: en-us
title: fahrizain
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: true
enableEmoji: true
mainsections: ["posts"]

publishDir: "public"

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 10

params:
    # env
    env: production

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    ShowAllPagesInArchive: true
    ShowPageNums: true

    math: true

    # analytics
    GoogleAnalyticsID: G-27DEESLMGL

    author: "Affandy Fahrizain"
    comments: true
    label:
      icon: "favicon-32x32.png"

    images:
    - android-chrome-512x512.png

    cover:
      hiddenInList: true # hide on list pages and home

    frontmatter:
      date:
        - publishDate
        - :filename
        - date
        - :fileModTime
      publishDate:
        - publishDate
        - :filename
        - date
        - :fileModTime
        
    meta:
      favicon: true

    assets:
      disableHLJS: true
      favicon: "favicon.ico"
      favicon16x16: "favicon-16x16.png"
      favicon32x32: "favicon-32x32.png"
      apple_touch_icon: "apple-touch-icon.png"

    
    pygmentsUseClasses: true
    markup:
      highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: catppuccin-frappe

    social:
      twitter: fhrzn_
      linkedin: Affandy Fahrizain


    homeInfoParams:
      Title: "Hello! \U0001F44B"
      Content: I'm a passionate AI & Data Engineer who currently exploring NLP and Speech Recognition at Kata.ai and Jakarta AI Research. Always up for chats about software, data, and AI/ML. Let's connect! 🚀
    socialIcons:
    - name: email
      url: mailto:affahrizain@gmail.com
    - name: linkedin
      url: https://www.linkedin.com/in/fahrizainn
    - name: github
      url: https://github.com/fhrzn
    - name: twitter
      url: https://twitter.com/fhrzn_
    - name: youtube
      url: https://www.youtube.com/@affahrizain
    - name: medium
      url: https://medium.com/@fahrizain

    # profile-mode
    profileMode:
      enabled: false # needs to be explicitly set
      title: "Hey, I’m Affandy \U0001F44B"
      subtitle: "With 2+ years of experience in both AI and Data Engineering, I develop innovative solutions such as FAQ automation, product recommendations, image search, and voice agents. I also design data transformation pipelines that enhance analytics and support informed decision-making."
      imageUrl: "https://media.licdn.com/dms/image/v2/D5603AQGtQ_6ORilufg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1704482632498?e=1753315200&v=beta&t=0x9uIT26IR7qyVuvPA_cneYXlPRAmneXXnLI-UNIf8o"
      imageWidth: 200
      imageHeight: 200
      imageTitle: my image
      
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

menu:
    main:
    - identifier: posts
      name: Posts
      url: /
      weight: 10
    - identifier: profile
      name: Profile
      url: /profile/
      weight: 20
    - identifier: linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/fahrizainn/
      weight: 30